<?php

namespace AppBundle\Repository;

/**
 * ArmasExploradorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmasExploradorRepository extends \Doctrine\ORM\EntityRepository
{
}
