<?php

namespace AppBundle\Repository;

/**
 * ArmasMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmasMedicoRepository extends \Doctrine\ORM\EntityRepository
{
}
