<?php

namespace AppBundle\Repository;

/**
 * ArmasAsaltoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmasAsaltoRepository extends \Doctrine\ORM\EntityRepository
{
}
