<?php

namespace AppBundle\Repository;

/**
 * ArmasApoyoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmasApoyoRepository extends \Doctrine\ORM\EntityRepository
{
}
